### ISSUE TITLE
No firmware update security?

### ISSUE THREAD

**Issue by Ofenhed** [UltimateHackingKeyboard/bootloader#12]
It seems that the security features from [Securing Firmware Upgrades](https://www.crowdsupply.com/ugl/ultimate-hacking-keyboard/updates/1957) isn't in place.

**Comment by mondalaci** [comment]
This is not ready yet, indeed. Closing this issue in favor of https://github.com/UltimateHackingKeyboard/agent/issues/615 and https://github.com/UltimateHackingKeyboard/firmware/issues/109
