### ISSUE TITLE
Relax hardcoded timeout

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/bootloader#6]
Currently, the timeout of the K22 bootloader is hardcoded to 5s. It would be nice if this would be configurable, but constrained within a reasonable interval. >=1s would probably cut it.

**Comment by ErichStyger** [comment]
The timeout is configurable with the BCA (Bootloader configuration area). Should it simply be configured for 1 second instead of the 5 seconds?

**Comment by mondalaci** [comment]
What I meant is making the timeout configurable run-time. There's a dedicated memory region via which the application firmware and the bootloader of the right keyboard half can communicate. Using this dedicated region, the UHK will be able to reenumerate as the bootloader with an arbitrary timeout. Please let me deal with this soon, Erich.

**Comment by mondalaci** [comment]
This has been implemented.
