### ISSUE TITLE
Wish: 'proven' bootloader binary

### ISSUE THREAD

**Issue by ErichStyger** [UltimateHackingKeyboard/bootloader#8]
Wish:
It would be good to have a 'proven' bootloader as S19/S-Record available in the repo.
That way in any case I can program the bootloader e.g. with a J-Link in case I cannot (or do not want) to build it.

**Comment by mondalaci** [comment]
Great point, @ErichStyger!

I've just set up Travis CI to build the bootloader on every commit. The next step will be to make Travis not only build the firmware but also upload it to the releases section of the GitHub project automatically. This way, we'll always have up-to-date srec files available to the general public.

The same approach is planned to be used for the firmware repo.

**Comment by mondalaci** [comment]
I've uploaded a binary to the release section of the repo.
